// <auto-generated />
namespace Core.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class cardLogosEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cardLogosEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202105311321105_cardLogosEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
